#!/bin/bash

if [[ `whoami` != 'root' ]]
then
    echo "Not running as root."
    exit 1
fi

ip link set wlan0 up
ip address flush dev wlan0
ip address add 192.168.1.33/16 brd + dev wlan0
ip address add 192.168.1.34/16 brd + dev wlan0
ip address add 192.168.2.1/16 brd + dev wlan0
ip address add 192.168.2.2/16 brd + dev wlan0
ip route add default via 192.168.1.254 dev wlan0 onlink
